export const SUBSCRIPTION_CREATED_REQUEST = 'SUBSCRIPTION_CREATED_REQUEST';
export const SUBSCRIPTION_CREATED_SUCCESS = 'SUBSCRIPTION_CREATED_SUCCESS';
export const SUBSCRIPTION_CREATED_FAIL = 'SUBSCRIPTION_CREATED_FAIL';